github:
  user_or_org: ramonaoptics
channels:
  targets:
  -
    - ramonaoptics
travis:
  secure:
    BINSTAR_TOKEN: KUiTRTD2goc7hFEwjwbyUtau2QOpnYLirbVn7NqkluqFXUcIiyG2fXuk1jcjCBElJ6IOvEtZ3mh3ZPGkYShLTHyP+R6lhq/kkEAOEbnr4YsH4K5I9sTgxUr3q/i1vbs16RTCClhK2qTfY400WoIU7mrEeG0x86WgFUMUuNQGdNCdCLNTPce6I2EjeGUQVmKa9Fq+MpIZROylpitgcwJpptBNYU3zbmAZPOozgDETbj/CPPfAGPJTPvRVics3Jj1GqrUbZvJw7JN1+8gj6LUaqlDuicbUK463lkfwnhEDvjhhPnhj4k/iGJWx2HJDh9gObEA8A+iQqUSDrZi08yaz2fNtzOGidYznqB2UwTEPm0RW3OFq+whG0Agaa9Hianl9WhWGbxn5kXKuq2JvJ13fLboJInsI1W1kxYS/txhDgKWs2lAMnH9VkxiyHWAE1dlkcurgz1x6pFg1tbZ4zPAQUW63h+6km9yykl4i61rzeuDgxSAERYTw0pMtcvx31Vcw7HzIWgziNkIimBAxD8H2y8Y7/XN8TNxRZMdp8YySe5J44jkULWdTfJztWN0VfB9P7KZ7Lo2hSw6o+2OYhntAVVvuxMnkWWsAp8I820HPxQ6NVgyBzQtbZ9agba0ZlYe9mCPovKPZ9wDZIr6WtgiEX1KE4RSWKcS/BR2KAZEBys0=
